homeassistant:
  name: Casa
  latitude: 45.437164
  longitude: 10.970851
  elevation: 64
  unit_system: metric
  time_zone: Europe/Rome
  customize: !include includes/customize.yaml
  packages: !include_dir_named packages
cloud:
config:
updater:
discovery:
sun:
dialogflow:
ffmpeg:
downloader:
  download_dir: www
logbook:
  exclude:
    entities:
      - sensor.speedtest
      - sensor.date_countdown
      - sensor.wunderground
      - sensor.darksky
      - sensor.systemmonitor
    domains:
      - sun
      - ffmpeg
      - camera
      - android_ip_webcam
      - device_tracker
      - intent_script
      - zone
      - weblink
      - history_graph
      - panel_iframe
logger:
  default: critical
  logs:
    homeassistant.components.dialogflow: debug
recorder:
  purge_interval: 2
  purge_keep_days: 3
http:
   server_port: 8123
   base_url: !secret base_url_site
   ip_ban_enabled: True
   login_attempts_threshold: 5
   api_password: !secret http_password
   trusted_networks:
     - 127.0.0.1
     - ::1
     - 192.168.1.0/24
tts:
  - platform: google
    cache: true
    cache_dir: /config/www/vl/voice
mqtt:
  broker: core-mosquitto
  username: homeassistant
  password: !secret http_password

############
# Includes
############
notify: !include includes/notify.yaml
frontend: !include includes/frontend.yaml
ifttt: !include includes/ifttt.yaml
history: !include includes/history.yaml
group: !include includes/groups.yaml
media_player: !include includes/media_players.yaml
camera: !include includes/cameras.yaml
android_ip_webcam: !include includes/android_ip_webcams.yaml
device_tracker: !include includes/device_trackers.yaml
sensor: !include includes/sensors.yaml
input_select: !include includes/input_select.yaml
input_number: !include includes/input_number.yaml
intent_script: !include includes/intent_scripts.yaml
switch: !include includes/switches.yaml
scene: !include includes/scenes.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
zone: !include includes/zones.yaml
input_boolean: !include includes/input_boolean.yaml
weblink: !include includes/weblinks.yaml
light: !include includes/light.yaml
binary_sensor: !include includes/binary_sensor.yaml
alarm_control_panel: !include includes/alarm.yaml
history_graph: !include includes/history_graph.yaml
panel_iframe: !include includes/panel_iframes.yaml
