####################################################################################
#
# RPi GPIO
# 
####################################################################################
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
binary_sensor:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
  - platform: rpi_gpio
    ports:
      17: PIR Desk

switch:
#************** APRI CANCELLO ********************
  - platform: rpi_gpio
    invert_logic: true
    ports:
      22: Cancello