###############################################################################
#
#                                 RPI GPIO
#
###############################################################################
#------------------------------------------------------------------------------
switch:
#------------------------------------------------------------------------------
#******************************** APRI CANCELLO *******************************
  - platform: rpi_gpio
    invert_logic: false
    ports:
      22: Cancello
      23: Led
#------------------------------------------------------------------------------
sensor:
#------------------------------------------------------------------------------
#**************************** MODULO SENSORE TEMPERATURA **********************
  - platform: dht
    sensor: DHT11
    name: dht
    pin: 17
#    temperature_offset: 2.1
#    humidity_offset: -3.2
    monitored_conditions:
      - temperature
      - humidity
#******************************************************************************

#------------------------------------------------------------------------------
#binary_sensor:
#------------------------------------------------------------------------------
#  - platform: rpi_gpio
#    ports:
#      17: PIR Desk
#    invert_logic: true
#  - platform: template
#    sensors:
#      wired_motion_sensor_desktop:
#        friendly_name: "Wired Motion Sensor Desktop"
#        device_class: motion
#        delay_off:
#          seconds: 20
#        value_template: >-
#          {{ is_state('binary_sensor.pir_desk', 'on') }}