###############################################################################
#
#                             HASS THEME CONTROL
#
###############################################################################
#------------------------------------------------------------------------------
automation:
#------------------------------------------------------------------------------
  - alias: "Restart HA if automations are off"
    trigger:
      - platform: state
        entity_id: binary_sensor.automations_off
        to: 'on'
        for:
          minutes: 5
      - service: notify.notify
        data:
          message: "Le automazioni sono ferme."
#******************************************************************************
- alias: 'Set Day theme at startup'
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    condition: sun
    after: sunrise
    after_offset: '+00:30:00'
  action:
  - service: frontend.set_theme
    data:
      name: default
#******************************************************************************
- alias: 'Set Night theme at startup'
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  condition:
    condition: sun
    after: sunset
  action:
  - service: frontend.set_theme
    data:
      name: darkblue
#******************************************************************************
- alias: Set Day Mode Theme after Sunrise
  trigger:
  - platform: sun
    event: sunrise
    offset: '+00:30:00'
  action:
  - service: frontend.set_theme
    data:
      name: default
#******************************************************************************
- alias: Set Night Mode Theme after Sunset
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: frontend.set_theme
    data:
      name: darkblue
#******************************************************************************