###############################################################################
#
#                              MUSIC IN THE KITCHEN
#
###############################################################################
#------------------------------------------------------------------------------
scene:
#------------------------------------------------------------------------------
  - name: Spegni Musica Cucina
    entities:
      script.arresta_musica_con_dash_button_cucina: on
  - name: Radio Successiva Cucina
    entities:
      script.radio_successiva_con_dash_button_cucina: on
  - name: Mute Volume Kitchen
    entities:
      script.mute_volume_kitchen: on
#------------------------------------------------------------------------------
input_number:
#------------------------------------------------------------------------------
  numero_radio_cucina:
    name: numero_radio_cucina
    min: 1
    max: 5
    step: 1
    initial: 1
  volume_radio_cucina:
    name: Volume Radio Cucina
    min: 0
    max: 10
    step: 1
    initial: 6
#------------------------------------------------------------------------------
input_boolean:
#------------------------------------------------------------------------------
  volume_radio_mute_cucina:
    name: Mute
    initial: off
    icon: mdi:volume-mute
#------------------------------------------------------------------------------
switch:
#------------------------------------------------------------------------------
  - platform: template
    switches:
      volume_radio_mute_cucina:
        friendly_name: Nabaztag Switch
        value_template: "{{ is_state('input_boolean.volume_radio_mute_cucina', 'on') }}"
        turn_on:
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.volume_radio_mute_cucina
        - service: media_player.volume_mute
          data_template:
            entity_id: media_player.kitchen
            is_volume_muted: True
        turn_off:
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.volume_radio_mute_cucina
        - service: media_player.volume_mute
          data_template:
            entity_id: media_player.kitchen
            is_volume_muted: False
#------------------------------------------------------------------------------
script:
#------------------------------------------------------------------------------
  arresta_musica_con_dash_button_cucina:
    alias: Arresta Musica con Dash Button Cucina
    sequence:
      - service: media_player.turn_off
        data:
          entity_id: media_player.kitchen
      - service: input_number.set_value
        data_template:
          entity_id: input_number.numero_radio_cucina
          value: '1.0'
  mute_volume_kitchen:
    alias: Toggle Media Kitchen Volume to Mute
    sequence:
      - service: media_player.turn_off
        data:
          entity_id: media_player.kitchen
      - service: input_number.set_value
        data_template:
          entity_id: input_number.numero_radio_cucina
          value: '1.0'
#******************************************************************************
  radio_successiva_con_dash_button_cucina:
    alias: Radio Successiva con Dash Button Cucina
    sequence:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.kitchen
        volume_level: {{ states('input_select.volume_radio_cucina')}}
    - service: media_player.play_media
      data_template:
        entity_id: media_player.kitchen
        media_content_id: >
          {% if is_state("input_number.numero_radio_cucina", "1.0") %}
            http://mp3channels.webradio.antenne.de/workout-hits.aac
          {%-elif is_state("input_number.numero_radio_cucina", "2.0") %}
            http://radiostream.flaixfm.cat:8002/;stream.nsv
          {%-elif is_state("input_number.numero_radio_cucina", "3.0") %}
            http://streaming.novaentertainment.com.au/nova100
          {%-elif is_state("input_number.numero_radio_cucina", "4.0") %}
            http://streaming.novaentertainment.com.au/smooth915 
          {%-elif is_state("input_number.numero_radio_cucina", "5.0") %}
            http://shoutcast.sbs.com.au/SBSChill
          {% else %}
            "None"
          {% endif %}
        media_content_type: 'audio/mp4'
    - service: input_number.set_value
      data_template:
        entity_id: input_number.numero_radio_cucina
        value: '{{ states.input_number.numero_radio_cucina.state | int + 1.0 }}'
#------------------------------------------------------------------------------
automation:
#------------------------------------------------------------------------------
  - alias: Resetta numero radio
    trigger:
    - platform: state
      entity_id: input_number.numero_radio_cucina
      to: "6.0"
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.numero_radio_cucina
        value: '1.0'
#******************************************************************************
  - alias: Cambia volume cucina
    trigger:
    - platform: state
      entity_id: input_number.volume_radio_cucina
    action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.kitchen
        volume_level: {{ states('input_select.volume_radio_cucina')}}
