############################################################
#
# Automazioni legate alla presenza
#
############################################################
#*******************************************************************************
#*******************************************************************************
binary_sensor:
#*******************************************************************************
#*******************************************************************************
  - platform: template
    sensors:
      mauro:
        friendly_name: "mauro"
        entity_id:
          - device_tracker.ec9bf3074845
          - device_tracker.f823b2ea1ff1
          - device_tracker.mauropersonale
          - device_tracker.maurolavoro
        value_template: >-
          {{ is_state('device_tracker.ec9bf3074845', 'home')
             or is_state('device_tracker.f823b2ea1ff1', 'home')
             or is_state('device_tracker.mauropersonale', 'home')
             or is_state('device_tracker.maurolavoro', 'home') }}
      max:
        friendly_name: "max"
        entity_id:
          - device_tracker.a039f73be2c7
          - device_tracker.28c671063a1f
          - device_tracker.maxpersonale
          - device_tracker.maxlavoro
        value_template: >-
          {{ is_state('device_tracker.a039f73be2c7', 'home')
             or is_state('device_tracker.28c671063a1f', 'home')
             or is_state('device_tracker.maxpersonale', 'home')
             or is_state('device_tracker.maxlavoro', 'home') }}
input_boolean:
  mxhome:
    name: Mx
    initial: off
    icon: mdi:account
  muhome:
    name: Mu
    initial: off
    icon: mdi:account

automation:
  - alias: Max Away
    trigger:
      - platform: state
        entity_id: binary_sensor.max
        to: 'off'
        for:
          minutes: 2
    condition:
      - condition: state
        entity_id: input_boolean.mxhome
        state: 'on'
    action:
        service: homeassistant.turn_off
        entity_id: input_boolean.mxhome
#***********************************************************************************
  - alias: Max Home
    trigger:
      - platform: state
        entity_id: binary_sensor.max
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.mxhome
        state: 'off'
    action:
        service: homeassistant.turn_on
        entity_id: input_boolean.mxhome
#***********************************************************************************
  - alias: Mauro Away
    trigger:
      - platform: state
        entity_id: binary_sensor.mauro
        to: 'off'
        for:
          minutes: 2
    condition:
      - condition: state
        entity_id: input_boolean.muhome
        state: 'on'
    action:
        service: homeassistant.turn_off
        entity_id: input_boolean.muhome
#***********************************************************************************
  - alias: Mauro Home
    trigger:
      - platform: state
        entity_id: binary_sensor.mauro
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.muhome
        state: 'off'
    action:
        service: homeassistant.turn_on
        entity_id: input_boolean.muhome
#***********************************************************************************
#  - alias: Arriving home Max
#    trigger:
#      - platform: state
#        entity_id: input_boolean.mxhome
#        to: 'on'
#    condition:
#      condition: or
#      conditions:
#        - condition: sun
#          after: sunset
#          after_offset: "-1:00:00"
#        - condition: sun
#          before: sunrise
#          before_offset: "1:00:00"
#    action:
#        service: switch.turn_on
#        entity_id: switch.light_kitchen
#***********************************************************************************
#  - alias: Arriving home Max - Welcome
#    trigger:
#      - platform: state
#        entity_id: input_boolean.mxhome
#        to: 'on'
#        for:
#          seconds: 10
#    action:
#        service: script.turn_on
#        entity_id: script.welcome_home
#***********************************************************************************
#  - alias: Arriving home Mauro
#    trigger:
#      - platform: state
#        entity_id: input_boolean.muhome
#        to: 'on'
#    condition:
#      condition: or
#      conditions:
#        - condition: sun
#          after: sunset
#          after_offset: "-1:00:00"
#        - condition: sun
#          before: sunrise
#          before_offset: "1:00:00"
#    action:
#        service: switch.turn_on
#        entity_id: switch.light_kitchen
#***********************************************************************************
#  - alias: Leaving home Max
#    trigger:
#      - platform: state
#        entity_id: input_boolean.mxhome
#        to: 'off'
#    condition:
#      - condition: state
#        entity_id: input_boolean.muhome
#        state: 'off'
#    action:
#        service: scene.turn_on
#        entity_id: scene.buona_notte
#***********************************************************************************
#  - alias: Leaving home Mauro
#    trigger:
#      - platform: state
#        entity_id: input_boolean.muhome
#        to: 'off'
#    condition:
#      - condition: state
#        entity_id: input_boolean.mxhome
#        state: 'off'
#    action:
#        service: scene.turn_on
#        entity_id: scene.buona_notte
#***********************************************************************************
  - alias: Mu at Home Ringer
    trigger:
      - platform: state
        entity_id: binary_sensor.mauro
        to: 'on'
    condition:
      - condition: time
        after: '17:00:00'
        before: '18:30:00'
    action:
      - service: hassio.addon_stdin
        data:
          addon: local_audio_player
          input: "http://192.168.1.100:8123/local/tng-doorbell.wav"

  - alias: Mu at Home Notification
    trigger:
      - platform: state
        entity_id: binary_sensor.mauro
        to: 'on'
    action:
      - service: ifttt.trigger
        data: {"event":"TestHA_Trigger", "value1":"M@Home"}

#***********************************************************************************
  - alias: Pc Acceso
    trigger:
      - platform: state
        entity_id: sensor.computersalotto
        to: 'Online'
    action:
        service: ifttt.trigger
        data: {"event":"TestHA_Trigger", "value1":"Il pc è stato avviato"}
#***********************************************************************************