###############################################################################
#
#                                 RF SENSORS
#
###############################################################################
#------------------------------------------------------------------------------
sensor:
#------------------------------------------------------------------------------
  - platform: mqtt
    state_topic: "sensors/rf/receiver"
    name: "RF Receiver"
  - platform: mqtt
    state_topic: "sensors/us/receiver"
    name: "US Receiver"
  - platform: mqtt
    state_topic: "sensors/rf/receiver2"
    name: "RF Receiver 2"
#------------------------------------------------------------------------------
binary_sensor:
#------------------------------------------------------------------------------
#******************************   LETTO   *************************************
  - platform: template
    sensors:
      motion_sensor_rf_1:
        friendly_name: "Motion Sensor RF 1"
        device_class: motion
        delay_off:
          seconds: 20
        value_template: >-
          {{ is_state('sensor.rf_receiver', '13679406') }}
#****************************   SCRIVANIA  *************************************
  - platform: template
    sensors:
      motion_sensor_rf_2:
        friendly_name: "Motion Sensor RF 2"
        device_class: motion
        delay_off:
          seconds: 240
        value_template: >-
          {{ is_state('sensor.rf_receiver', '1118556') }}
#*******************************   BAGNO   ************************************
  - platform: template
    sensors:
      motion_sensor_rf_3:
        friendly_name: "Motion Sensor RF 3"
        device_class: motion
        value_template: >-
          {{ is_state('sensor.rf_receiver', '1855836') }}
#******************************* CUCINA 2 *************************************
  - platform: template
    sensors:
      motion_sensor_rf_4:
        friendly_name: "Motion Sensor RF 4"
        device_class: motion
        delay_off:
          seconds: 120
        value_template: >-
          {{ is_state('sensor.rf_receiver', '7815516') }}
#***************************** Bagno Uscita ***********************************
  - platform: template
    sensors:
      motion_sensor_rf_5:
        friendly_name: "Motion Sensor RF 5"
        device_class: motion
        value_template: >-
          {{ is_state('sensor.rf_receiver', '12916060') }}
#************************* Telecomando Luci Posizione D************************
  - platform: template
    sensors:
# luci salotto spente
      telecomando_rf_1d_off:
        friendly_name: "Telecomando RF 1D Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5755907') }}
# luci salotto accese
      telecomando_rf_1d_on:
        friendly_name: "Telecomando RF 1D On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5755916') }}
# blu
      telecomando_rf_2d_off:
        friendly_name: "Telecomando RF 2D Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5731331') }}
# modalità film
      telecomando_rf_2d_on:
        friendly_name: "Telecomando RF 2D On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5731340') }}
# arancio
      telecomando_rf_3d_off:
        friendly_name: "Telecomando RF 3D Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5725187') }}
# azzurro
      telecomando_rf_3d_on:
        friendly_name: "Telecomando RF 3D On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '5725196') }}
#****************** Telecomando Bianco Luci Posizione IV***********************
  - platform: template
    sensors:
# luci salotto spente
      telecomando_rf_1d_off:
        friendly_name: "Telecomando RF 1D Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2326706688') }}
# luci salotto accese
      telecomando_rf_1d_on:
        friendly_name: "Telecomando RF 1IV On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2192488960') }}
# blu
      telecomando_rf_2d_off:
        friendly_name: "Telecomando RF 2IV Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2729359872') }}
# modalità film
      telecomando_rf_2d_on:
        friendly_name: "Telecomando RF 2IV On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2897132032') }}
# arancio
      telecomando_rf_3d_off:
        friendly_name: "Telecomando RF 3IV Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2460924416') }}
# azzurro
      telecomando_rf_3d_on:
        friendly_name: "Telecomando RF 3IV On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2628696576') }}
# arancio
      telecomando_rf_3d_off:
        friendly_name: "Telecomando RF 4IV Off"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2746137088') }}
# azzurro
      telecomando_rf_3d_on:
        friendly_name: "Telecomando RF 4IV On"
        value_template: >-
          {{ is_state('sensor.rf_receiver', '2477701632') }}
#Isnatch IV
#-------------------------------------------------------------------------------
automation:
#-------------------------------------------------------------------------------
#******************************   LETTO   **************************************
  - alias: 'Accendi luce sotto il letto'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_rf_1
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.camera
      - service: mqtt.publish
        data:
          topic: 'sensors/rf/receiver'
          payload: '1111111'
          retain: 'true'
#******************************************************************************
  - alias: 'Spegni luce sotto il letto'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_rf_1
        to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.camera
#****************************   SCRIVANIA  ************************************
  - alias: 'Accendi luce scrivania'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_rf_2
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.permetti_accensione_luci
        state: 'on'
    action:
      - service: light.turn_on
        entity_id: light.light_desk
      - service: mqtt.publish
        data:
          topic: 'sensors/rf/receiver'
          payload: '1111111'
          retain: 'true'
#******************************************************************************
  - alias: 'Spegni luce scrivania'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_rf_2
        to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.light_desk
#*******************************   BAGNO   ************************************
  - alias: 'Accendi luce bagno'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_rf_3
        to: 'on'
    condition:
      - condition: time
        after: '7:10:00'
        before: '01:00:00'
    action:
      - service: timer.cancel
        entity_id: timer.spegnimento_bagno
      - service: light.turn_on
        entity_id: light.bagno
      - service: mqtt.publish
        data:
          topic: 'sensors/rf/receiver'
          payload: '1111111'
          retain: 'true'
      - service: timer.start
        entity_id: timer.spegnimento_automatico_bagno
      - service: timer.cancel
        entity_id: timer.spegnimento_bagno
#******************************************************************************
  - alias: 'Spegni luce bagno'
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.spegnimento_bagno
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.spegnimento_automatico_bagno
    action:
      - service: light.turn_off
        entity_id: light.bagno
      - service: timer.cancel
        entity_id: timer.spegnimento_bagno
      - service: timer.cancel
        entity_id: timer.spegnimento_automatico_bagno
#******************************************************************************
  - alias: 'Conto alla rovescia spegnimento luce bagno se si passa davanti al sensore di uscita'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_rf_5
        to: 'on'
    action:
      - service: mqtt.publish
        data:
          topic: 'sensors/rf/receiver'
          payload: '1111111'
          retain: 'true'
      - service: timer.start
        entity_id: timer.spegnimento_bagno
#******************************************************************************
  - alias: 'Spegne luci salotto'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_1d_off
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.luci_sala_spente
#******************************************************************************
  - alias: 'Accende luci salotto'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_1d_on
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.luci_sala_accese
#******************************************************************************
  - alias: 'Striscia led aliceblue'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_2d_off
        to: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.led_strip
          color_name: "aliceblue"
          brightness_pct: "100"
#******************************************************************************
  - alias: 'Modalità film'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_2d_on
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.film
#******************************************************************************
  - alias: 'Striscia Led chocolate'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_3d_off
        to: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.led_strip
          color_name: "chocolate"
          brightness_pct: "100"
#******************************************************************************
  - alias: 'Striscia led orchid'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_3d_on
        to: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.led_strip
          color_name: "orchid"
          brightness_pct: "100"
#******************************************************************************
  - alias: 'Accende luci salotto 1'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_1iv_on
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.luci_sala_accese
  - alias: 'Accende luci salotto 2'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_1iv_off
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.luci_sala_accese
  - alias: 'Accende luci salotto 3'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_2iv_on
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.luci_sala_accese
  - alias: 'Accende luci salotto 4'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_2iv_off
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.luci_sala_accese
  - alias: 'Accende luci salotto 5'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_3iv_on
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.luci_sala_accese
  - alias: 'Accende luci salotto 6'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_3iv_off
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.luci_sala_accese
  - alias: 'Accende luci salotto 7'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_4iv_on
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.luci_sala_accese
  - alias: 'Accende luci salotto 8'
    trigger:
      - platform: state
        entity_id: binary_sensor.telecomando_rf_4iv_off
        to: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.luci_sala_accese
#******************************************************************************
timer:
  spegnimento_automatico_bagno:
    duration: '00:10:00'
  spegnimento_bagno:
    duration: '00:00:3'
#******************************************************************************